language: python
python:
- '2.7'
- '3.5'
addons:
  apt_packages:
  - pandoc
install:
- pip install -r requirements-dev.txt
script: py.test --cov
after_success: coveralls
deploy:
  provider: pypi
  user: bmweiner
  password:
    secure: NxQW24lU8FdbsFrkmbf8kM0PhjjfQcCrbhf/mJ/EKBDl5H2bLXdn1LaI7m+0m1Oyq1uU6oepAfnxtVEp58xDFW99W3x00vNQCgY/46X1rR4EfmIwZ69W/ZDbY/3seyQKd3K7boqKcXBl0TfbCg6oHSJxCY2JYxpD/Ccn8C/QRRZ2h7CXcFBoAtn+5VwSW+wNLdgia//yvuSiDcvj9TsVA8ryZ0gV1JrCaEzL0qk6h/YnVu86Zh/3oPlaPU7OdW0SQ6kBD+iIp01KVEP+K7GVZLi4ZlL9HJe1jV9DH1wwSvaTxGMK3mwUXvqqYh8xIc7Jwn93QT7EfZaUx0P6hRjlRNX8XTj2CLt2qlQC9BRt4EIoi8ZALjcTaRs8qKrkGQl5tFrbaWdp6TAUGsJ0nTt6t3EQdTlk/3Rh5ySIHiZ5yg1dwoBku2pjah/1m9/HiNsR/WVKmG4XZ+F1EbM+I54a2Y6oz+LF+oTJv2ikeXbN2TcL+6kRivQbDIzkMSd2wEk0dOH01rVbAHSW5NXO32Xllsi+cwZJO0YvyD6EkmFp3fTX4VZf4HmZwzLIZs96vac/iU/MZsR9TtsjaIJnA0I/wu9zFeDn5foWk+a/rc14iL53OotMnFSJez6OLEjRGz1sjRqQX09+kLikYH+kdGrOILd8LAvjhcG6J7nVKpefm3w=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bmweiner/skillful
    condition: "$TRAVIS_PYTHON_VERSION = '2.7'"
