language: python
python:
  - '2.7'
  - '3.5'
addons:
  apt_packages:
    - pandoc
install:
  - pip install -r travis-requirements.txt
script: py.test --cov 
after_success:
  coveralls
deploy:
  provider: pypi
  user: bmweiner
  password:
    secure: KxALjD1DTZeNFwrlXGpcFKbyjQaedxi49mFEaEuz6fwHNCDHDCjNMTVOAsJ9q05zjIX4srVgOlRg8J0UClZ+gq0DuB3r01z0ktc2+BM8+yVQxDPhzIF/gKp/4q5ETRHs2u0vFqDMA2HcpwFoU2v9WlFfN1MBbkb6Xgrm7KNyQ0IcKpBe4uxC+FbT8ufLYvEuTTHjjrN6/rQicjNiwH2DALYOJv6SNGOGBRO2B8Ih7EsE9XjTiVOpd9aRCV7blxtyPJA5IOt36i+kwXje3ApDjPFMn2NjlDSOe19stwAXdcbglDkXfsXEAKfxNCPPdEOOO0XMpcTpn4VpIwkXkCUAKYI5fInWf/tPh85yJA+4YUC4sGAa8h4yo8tR3myrLDSVhk5sxldwiykpg+PH3Lp49lm4mSFkvt2W8U8lJo+hrcwKDft+MQhMAcjZ7VTggEpb6O3ktfaUOgev1G2ZyAafQCN3bHyypOZCK1DKxh6b9NCbdXg0pIY5Hv/deDdYswL9jZqF9bEI23Rem8Ii6VbKmPaRtSotVLu7VPlZep0bGzKpCdie7KkfqHgDSUV5C7eCjDCtdY0Ah0DDvcbIIFx3P5yaXnsnKSwXMhDMmE8qBsBpT4iH2vY5yaEUob5OUfTaNcLyYd40DOvK76WVKC+UjPhcwypCrf6n+mxKhVI1B/g=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bmweiner/skillful
    condition: $TRAVIS_PYTHON_VERSION = '2.7'
